name: Deploy
on: 
  push: 
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  Repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        id: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: echo {{steps.login.outcome}}
        continue-on-error: false
      - name: Set up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v1
        continue-on-error: false
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context:  .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-test:${{github.run_number}}
        continue-on-error: false
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
        
        


